### ISSUE TITLE
Add a task for dev releases

### ISSUE THREAD

**Issue by kitsonk** [dojo/grunt-dojo2#144]
**Enhancement** 

It would be good to have a task that would do a dry run release of the package and then de-archive it to the `node_modules` of another package.  This would make it more "fool proof" to do development of packages than having to leverage `grunt link` or `npm link` since it seems increasingly difficult with the way npm 5 handles things and the way that TypeScript resolves types with symbolic links.

**Comment by agubler** [comment]
By "de-archive" do you mean unpack the `tar`? Because it is probably best if we encourage users to actually `npm install /location/data/dist/dojo-2-data-2.0.0-alpha.1.tgz` in the desired package as it will install and dedup any additional dependencies. Where as copying and unpacking does not.

I don't think that the subsequent install should be part of the command but I do see the benefit of effectively aliasing the `grunt release --dry-run` task.

**Comment by kitsonk** [comment]
Oh, yeah, I forgot about that way... 😖  Do you see a benefit in something like `grunt dev-release` where we put the dry run in some known location in the package and then in the other package something like `grunt dev-install ../core` which would look for the release and do the `npm install ../core/dist/dev-release.tgz` or whatever?

**Comment by agubler** [comment]
I think something like `grunt dev-release` which is effectively an alias of `grunt release` with the appropriate options would be useful. 

Perhaps we could symlink the `tgz` file and then something like `grunt dev-install` would potentially only need to take the package name `grunt dev-install @dojo/core` otherwise having to specify the path only offers minimal usefulness over just running `npm install ...`.

**Comment by kitsonk** [comment]
I guess the thing I was trying to solve in my head is not having to remember `dojo-2-data-2.0.0-alpha.1.tgz` to do it... it we output the archive to a consistent name and location in a package, it would be easy to do an `npm install ../core/dev/package.tgz` instead of having to remember what it was like 5 steps ago.

**Comment by agubler** [comment]
That is a little bit annoying I grant you.

* So certainly an alias for development (effectively dry-run with skip checks)
* Then perhaps a command that takes a path to a package and installs a `tgz` file that exists in `dist`? Means don't have to worry about the name or create an archive with a special development name?

**Comment by kitsonk** [comment]
Not strictly related to the release process, but would be nice to have as part of the improvements.
